### PR TITLE
Support comments

### PR DESCRIPTION
**Pull request by k-bx**
Also: improve error reporting

### CODE REVIEW

**Review by pjsier — CHANGES_REQUESTED** [review]
Thanks for the PR! This looks great other than the clippy and rustfmt errors. Those look like quick fixes so I can go ahead and approve and merge once those are passing

**Comment by pjsier** [comment]
Looks like there's a test still failing, not sure if it was caused by fixing a clippy lint that was a false positive?

**Comment by k-bx** [comment]
> Looks like there's a test still failing, not sure if it was caused by fixing a clippy lint that was a false positive?

My bad, should be fixed now.

**Review by pjsier — APPROVED** [review]
Thanks for those updates, looks great!

**Pull request merged**
